name: 02 Workflow Events

on:
  push:
  pull_request:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes
  workflow_dispatch:


jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "I've been triggered by an ${{ github.event_name }} event"
