name: 05 - 1 - Event Filters And Activity Types

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Event Filters And Activity Types 5.1
        run: |
          echo "Triggered by pull request event with types: opened, synchronize, or reopened"
