name: 05 - 2 - Event Filters And Activity Types

on:
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Event Filters And Activity Types 5.2
        run: |
          echo "Triggered by pull request event with type: closed"