name: 07 - Expressions
run-name: 07 - Expressions
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: '[debug] Print start-up information'
        if: ${{ inputs.debug }}
        run: |
          echo "Debug mode is enabled"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run number: ${{ github.run_number }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
      - name: '[debug] Print trigger information'
        if: ${{ inputs.debug && github.event_name == 'workflow_dispatch' && github.ref  == 'refs/heads/main' }}
        run: |
          echo "Triggered by event: ${{ github.event_name }}"
          echo "Event details: ${{ toJson(github.event) }}"